server:
  port: 9000
  host: "0.0.0.0"

log:
  path: "logs"

pong_time:
  version: 

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "life_watch"