# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: deploy serverless scf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o life-watcher

    - name: create zip folder
      run: mkdir -p ./src/conf

    - name: move binary to src folder
      run: cp ./life-watcher ./scf_bootstrap ./src && cp ./conf/config_template.yml ./src/conf/config_template.yml

    - name: deploy serverless
      uses: woodyyan/tencent-serverless-action@main
      env: # 环境变量
        STAGE: prod #您的部署环境
        SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key
        APP_CONFIG_SERVER_PORT: 9000
        APP_CONFIG_SERVER_HOST: 0.0.0.0
        APP_CONFIG_DATABASE_DRIVER: mysql
        APP_CONFIG_DATABASE_HOST: ${{ secrets.APP_CONFIG_DATABASE_HOST }}
        APP_CONFIG_DATABASE_PORT: ${{ secrets.APP_CONFIG_DATABASE_PORT }}
        APP_CONFIG_DATABASE_USER: ${{ secrets.APP_CONFIG_DATABASE_USER }}
        APP_CONFIG_DATABASE_PASSWORD: ${{ secrets.APP_CONFIG_DATABASE_PASSWORD }}
        APP_CONFIG_DATABASE_NAME: ${{ secrets.APP_CONFIG_DATABASE_NAME }}
        APP_CONFIG_DATABASE_TLS: ${{ secrets.APP_CONFIG_DATABASE_TLS }}
        APP_REQUEST_KEY: ${{  vars.APP_SCF_REQUEST_KEY }}
        APP_CONFIG_LOG_PATH: /tmp/logs
        APP_CONFIG_PONG_TIME_VERSION: ${{ github.event.head_commit.timestamp }}
